# Code generated by AI based on the following prompt:
# Write a function to handle the 'Buy Now' button press, which triggers the in-app purchase flow and unlocks the full version of the app

print('Hello from Purchase.js!')